---
name: WWW-XKCD-AsText
version: 0.001
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: retrieve text versions of comics on www.xkcd.com
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  Class::Data::Accessor: 0.04001
  HTML::Entities: 1.35
  HTML::TokeParser::Simple: 3.15
  LWP::UserAgent: 2.036
  URI: 1.35
build_requires:
  Test::More: 0
provides:
  WWW::XKCD::AsText:
    file: lib/WWW/XKCD/AsText.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
